/** Participant-facing guided instructions — one array of speakable paragraphs per day (1–60). */
export const GUIDED_DO_THIS: ReadonlyArray<ReadonlyArray<string>> = [
  [
    "When you wake, stay quiet for a moment before reaching for your phone or beginning the day.",
    "Ask yourself: What was happening just before I woke?",
    "Take the first thing that appears—whether that is an image, a place, a person, a feeling, a phrase, or a movement—and record it immediately.",
    "A fragment is enough.",
    "If you remember that you were dreaming but nothing else, write: Dreamed. No details.",
    "Do not fill in missing pieces.",
  ],
  [
    "Choose two ordinary events that will probably happen today.",
    "For example: when you open the refrigerator, remember to touch the handle twice; or when you turn off a light, remember to look at your hand.",
    "Choose your own cues.",
    "Do not set reminders.",
    "Let the event itself trigger the memory.",
  ],
  [
    "Get comfortable.",
    "Move through these areas one at a time: hands, arms, shoulders, jaw, abdomen, legs, and feet.",
    "For each area, gently tense it for about three seconds, release it completely, and feel the difference for a few seconds.",
    "Keep the tension mild.",
    "After the feet, let the whole body rest for one minute without doing anything else.",
  ],
  [
    "Settle somewhere comfortable for about five minutes.",
    "Let your breathing happen naturally.",
    "Choose one place where the breath is easy to feel—the nostrils, the chest, or the abdomen—and keep your attention there.",
    "When you notice that your mind has wandered, return to the same physical sensation.",
    "Do not change the breath.",
    "Do not try to stop thoughts.",
    "Just return.",
  ],
  [
    "Choose one small point in the center of your palm.",
    "Touch it lightly with one fingertip for several seconds and notice the location.",
    "Remove your finger, keep your eyes closed, and place your attention on the same point.",
    "Recreate the memory of contact.",
    "Try different versions if they help: a fingertip pressing lightly, warmth at the point, a tiny pulse, or a soft tap.",
    "You are not trying to produce a particular sensation.",
    "Try the image and notice how it feels.",
    "Repeat with the other hand.",
  ],
  [
    "Use one fingertip to slowly trace a line from the center of your wrist to the tip of your middle finger.",
    "Repeat the physical trace two or three times, then stop touching and close your eyes.",
    "Recreate the same moving path internally through wrist, palm, finger, and fingertip, then reverse it.",
    "Experiment with an image that makes the movement easy to follow—a fingertip, a soft brush, a pencil eraser, or a narrow stream of water.",
    "Keep the path slow enough to feel where your attention is moving.",
    "Repeat on the other hand.",
  ],
  [
    "Choose a small area in the center of one palm.",
    "With a fingertip from the other hand, slowly draw a small circle there several times, then stop touching and close your eyes.",
    "Continue the same circle in imagination and keep it slow.",
    "After a minute, reverse direction.",
    "Then try changing the imagined contact—a fingertip, a rounded brush, a small ball, or a swirl of warm water—and use whichever version makes the circular motion easiest to follow.",
    "Repeat with the other hand.",
  ],
  [
    "Hold one hand open.",
    "Imagine a soft brush moving from the wrist, across the palm, and out through the fingertips, then bring it back the same way.",
    "Keep the motion slow.",
    "Try changing the width of the imagined brush: one finger wide, three fingers wide, or the full width of the palm.",
    "You can physically brush the path once first if that helps, then remove the physical touch and continue in imagination.",
    "Repeat with the other hand.",
  ],
  [
    "Choose one hand.",
    "Move imagined touch slowly through the thumb from base to tip, then the index finger, middle finger, ring finger, and little finger.",
    "Reverse direction, then sweep through all five fingers together.",
    "Try switching between one finger, two fingers, and the whole hand.",
    "Repeat with the other hand.",
  ],
  [
    "Start with one foot.",
    "Choose a point on the sole and touch it briefly, remove the touch, and recreate it in imagination.",
    "Then try a line from heel to toes, a small circle in the center of the sole, or a broad brush across the whole foot.",
    "Move through the toes one at a time, then repeat with the other foot.",
    "Use whatever imagined contact makes the path easiest to follow.",
  ],
  [
    "Start at the fingertips of one hand.",
    "Imagine a narrow line of contact moving slowly through fingers, palm, wrist, forearm, elbow, upper arm, and shoulder, then bring it back down.",
    "Do not jump between areas.",
    "Keep one continuous path.",
    "Try a fingertip, brush, stream of water, or any image that makes the movement easy to follow.",
    "Repeat on the other arm.",
  ],
  [
    "Start at the toes of one foot.",
    "Imagine a narrow line moving through foot, ankle, lower leg, knee, thigh, and hip, then return to the toes and repeat several times.",
    "Now make the imagined contact wider.",
    "Instead of a thin line, imagine a broad sweep moving through the whole leg.",
    "Repeat with the other leg.",
  ],
  [
    "Choose one hand and forearm.",
    "Instead of imagining contact moving across the skin, imagine something passing through the whole space of the hand—such as a soft sponge, a wave, a warm current from fingertips to elbow, or a sphere slowly moving along the arm.",
    "Keep the physical arm still.",
    "You do not need to visualize anatomy.",
    "Just imagine movement through volume instead of across a surface.",
    "Repeat on the other side.",
  ],
  [
    "Lie or sit comfortably.",
    "Begin at the feet and move imagined sensation slowly through feet, legs, hips, torso, shoulders, arms, and hands, then back to the shoulders, neck, and head.",
    "Then reverse the route.",
    "Use a line, brush, wave, current, or any other image that stays easy to follow.",
    "Do not rush through areas just to complete the circuit.",
    "Keep the movement continuous.",
  ],
  [
    "Choose one physical sensation: breath at the nostrils, pressure where your hands touch, or contact between your body and the chair or bed.",
    "Stay with that one point for about seven minutes.",
    "When attention drifts, return to the same place.",
    "Do not try to stop thought.",
    "The practice is: find it, lose it, find it again.",
  ],
  [
    "Use the same kind of single-point focus as yesterday.",
    "When you realize you have been thinking about something else, say one word silently: drift.",
    "Then return.",
    "Do not analyze the thought.",
    "Do not restart the timer.",
    "Do not judge how long you were gone.",
    "Just catch the change and come back.",
  ],
  [
    "Begin with one minute of attention on the breath, then stop selecting.",
    "For about five minutes, let sounds, body sensations, darkness behind the eyes, thoughts, and images come and go.",
    "Do not follow any one thing for long.",
    "If a thought carries you away, notice it and reopen the field.",
  ],
  [
    "For about four minutes, alternate every thirty seconds between narrow and wide.",
    "Narrow: choose one tiny point in one hand.",
    "Wide: feel the whole body at once.",
    "Then spend about two minutes with sound: narrow on one specific sound, wide on the entire sound field.",
    "Move back and forth deliberately.",
  ],
  [
    "Choose one image from Days 5–14—a brush, a circle, a wave, a line, or a current—and run it through one hand or forearm for about five minutes.",
    "When the imagined movement disappears, restart it where you lost it.",
    "Keep the physical body still.",
    "Do not switch to a different image because the first one fades.",
  ],
  [
    "Get comfortable.",
    "Keep a light awareness of natural breathing.",
    "At the same time, imagine a brush moving slowly from one hand up the arm and back.",
    "Let the imagined movement stay in the foreground and the breath remain in the background.",
    "If one disappears, restore it and continue.",
    "Do not worry if attention shifts back and forth at first.",
    "Three to five minutes is enough.",
  ],
  [
    "Do this at your normal bedtime.",
    "Choose one simple thread: the breath, a slow circle in one palm, or a slow brushing motion along one hand.",
    "Keep it gentle.",
    "You are not trying to stay awake.",
    "You are not waiting for anything unusual.",
    "Let yourself fall asleep normally while occasionally remembering the thread.",
    "If it disappears, let it disappear.",
    "If you notice it again, resume lightly.",
  ],
  [
    "Read a few recent dream fragments.",
    "Choose three details that would have been unusual, impossible, or out of place if they happened while awake—for example a person somewhere they should not be, a room arranged incorrectly, impossible movement, technology behaving strangely, a sudden location change, or someone appearing who is no longer alive.",
    "Use your own examples.",
    "If recent recall is sparse, use any older dream you remember clearly.",
  ],
  [
    "Choose two natural events that are likely to happen today.",
    "For example: when you walk through your front door, remember to look closely at your surroundings; or when your phone rings, remember what you intended to do.",
    "Do not set reminders.",
    "Let the event itself trigger the memory.",
  ],
  [
    "A few times today, when something feels genuinely odd, repetitive, surprising, or dreamlike, stop and ask: Could I be dreaming?",
    "Then perform one simple test.",
    "Try either reading a short piece of text or a clock, looking away, then reading it again, or gently closing your nose and seeing whether breathing still feels possible.",
    "Do not perform checks constantly.",
    "The question matters more than the ritual.",
  ],
  [
    "Do this before bedtime, but not while trying to fall asleep.",
    "Recall one recent dream and choose one dream sign from it.",
    "Imagine the dream again.",
    "When the dream sign appears in imagination, stop and think: This is a dream.",
    "Then continue imagining the same dream while knowing that you are dreaming.",
    "Repeat the sequence a few times.",
  ],
  [
    "Get comfortable and prepare to sleep normally.",
    "Recall one dream sign and briefly imagine recognizing it and thinking: This is a dream.",
    "Repeat only until the intention feels clear, then stop rehearsing and let sleep come.",
    "Do not force the phrase for long periods.",
  ],
  [
    "If you wake from a dream during the night or early morning, stay comfortable, recall the dream, choose one dream sign, imagine returning to the dream, rehearse recognizing the sign, set the intention to notice the next dream, and return to sleep.",
    "Do not set an alarm for this exercise.",
    "If you do not wake naturally, use Day 26 at bedtime instead.",
  ],
  [
    "Each time you genuinely wake from sleep or a nap today, pause before getting absorbed in the day.",
    "Ask: Am I fully awake?",
    "Perform one calm state check, then continue normally.",
    "Do not repeat this every time you stand up or enter a room.",
    "Use waking as the cue.",
  ],
  [
    "Close your eyes and imagine that you suddenly realize: This is a dream.",
    "Then rehearse only the first few seconds.",
    "Pause, look closely at one nearby object, and touch one surface if you can.",
    "Stay with the scene instead of immediately trying to control everything.",
    "Repeat the short rehearsal a few times.",
  ],
  [
    "At normal bedtime, recall a recent dream, choose one dream sign, imagine recognizing it, form the intention to notice the next dream, and let sleep come naturally.",
    "If you wake naturally from a dream later, repeat the sequence once.",
    "Do not set an alarm.",
    "Do not extend wakefulness.",
    "Perform the method and let the night unfold.",
  ],
  [
    "At bedtime or during a comfortable rest, close your eyes and let them remain relaxed.",
    "Notice the darkness behind your eyelids.",
    "Do not search for shapes.",
    "Do not name every flicker.",
    "Do not try to make a picture.",
    "Just watch.",
    "If imagery begins, let it change by itself.",
  ],
  [
    "Lie comfortably with your eyes closed.",
    "Begin with ordinary sounds around you, then notice quieter sounds: your breathing, fabric moving, distant background noise, or faint internal sound if present.",
    "Do not search for unusual sounds.",
    "Do not invent them.",
    "Let hearing stay open.",
  ],
  [
    "Lie still enough to notice the body as one field.",
    "Do not brush, stir, or trace.",
    "Notice contact with the bed or chair, weight, temperature, breathing, and position.",
    "Let the body feel however it feels.",
  ],
  [
    "Close your eyes.",
    "For about twenty seconds, watch the visual field.",
    "Then listen to the auditory field.",
    "Then feel the bodily field.",
    "Repeat the cycle several times.",
    "Do not search for unusual content in any channel.",
    "Just move attention.",
  ],
  [
    "Repeat yesterday’s sequence: watch, listen, feel.",
    "This time, do not concentrate hard.",
    "Touch each channel lightly with attention, then move on.",
    "After several slower cycles, let the transitions become easier and less deliberate.",
    "When you finish, stop the exercise and sleep normally.",
  ],
  [
    "Begin with one familiar imagined object or tactile motion for about one minute—for example a circle in the palm, a brush across the hand, or a simple object.",
    "Then stop creating it and remain quietly attentive.",
    "If an image, sound, phrase, or movement-like impression appears without deliberate construction, observe it without developing it.",
    "Do not chase it.",
  ],
  [
    "Lie comfortably and keep a light awareness of where your hands seem to be, where your feet seem to be, the outline of your body, up and down, and left and right.",
    "Do not correct any change with movement unless you are uncomfortable.",
    "If everything feels completely ordinary, continue observing.",
  ],
  [
    "At your normal bedtime, watch the visual field briefly, listen briefly, and feel the body briefly.",
    "Stop cycling and let attention become passive.",
    "Allow sleep to come.",
    "If a spontaneous image, sound, phrase, or movement-like impression appears, observe it without chasing it.",
    "Do not try to stay awake.",
    "Do not wait for a specific event.",
  ],
  [
    "Lie comfortably and imagine your whole body rocking gently from side to side.",
    "Keep the movement small and slow: left, center, right, center.",
    "Do not watch yourself from outside.",
    "Feel the motion from inside.",
    "If it helps, physically rock once or twice first, then stop moving and recreate the same motion internally.",
  ],
  [
    "Lie still and imagine the whole body slowly rolling to one side as if turning over in bed.",
    "Do not move any muscles.",
    "Continue the imagined roll farther than a normal physical turn, then reverse direction.",
    "Stay in first-person perspective.",
    "You do not need to picture the room clearly.",
    "Focus on the felt rotation.",
  ],
  [
    "Imagine your whole body drifting several inches to the left while staying level, return to center, then drift to the right.",
    "Imagine a platform sliding smoothly beneath you.",
    "Keep the movement horizontal.",
    "Do not intentionally move your head or eyes.",
    "Repeat slowly.",
  ],
  [
    "Imagine the whole body becoming lighter and rising a few inches, pause, then settle back down.",
    "Repeat slowly: rise, pause, settle.",
    "Do not force a picture of the room below you.",
    "Prioritize the felt movement.",
    "If it helps, imagine water lifting you, an elevator rising, a platform moving upward, or simple upward motion.",
  ],
  [
    "Choose one arm and keep it completely still.",
    "Imagine reaching toward an object or point beyond comfortable physical reach, feeling the movement through shoulder, arm, hand, and fingers, then return.",
    "Next, reach farther than the physical arm could actually extend.",
    "Try upward and outward.",
    "Do not worry about anatomical realism.",
    "Follow the intended movement.",
  ],
  [
    "Choose one simple destination—the door, the ceiling, the foot of the bed, or a corner of the room.",
    "Keep your physical body still and imagine your point of view moving toward that location.",
    "Do not picture yourself traveling from outside.",
    "Move from first-person perspective, return to your starting point, and repeat.",
  ],
  [
    "Pick whichever motion from the last six days feels easiest: rock, roll, glide, float, reach, or move toward a point.",
    "Repeat only that motion for about five minutes.",
    "Do not switch because attention wanders.",
    "Restore the same motion and continue.",
    "As it becomes familiar, use less effort while keeping the movement clear.",
  ],
  [
    "At bedtime or during a relaxed session, relax the body and choose your strongest imagined movement.",
    "Create it deliberately for a short time, then gradually use less effort to maintain it.",
    "Notice whether it continues, fades, changes, or stops.",
    "If the movement changes, do not immediately rebuild the original version.",
    "Follow what is already happening.",
  ],
  [
    "At your normal bedtime, relax the body and choose one light anchor: breath, palm circle, or whole-body sensation.",
    "Briefly notice the visual field, sound, and body.",
    "Choose one motion from the move exercises, sustain it gently, use less effort, and allow sleep.",
    "Do not add extra techniques.",
  ],
  [
    "If you wake naturally during the night or early morning and still feel sleepy, stay comfortable, recall the dream if one is present, use one light anchor, choose one familiar motion, reduce effort, and return to sleep.",
    "Do not set an alarm for this exercise.",
    "If you do not wake naturally, use Day 47 at bedtime.",
  ],
  [
    "Use only relax, one anchor, one motion, reduce effort, and sleep.",
    "Do not cycle through every sense.",
    "Do not repeat several affirmations.",
    "Do not change motions.",
    "Keep the sequence small.",
  ],
  [
    "If you become lucid, pause, let the dream continue, and choose one familiar motion—roll, rise, float, or move toward a point.",
    "Perform it from first-person perspective and notice what changes.",
    "If no lucid dream occurs, use the shortened bedtime sequence from Day 49.",
  ],
  [
    "This exercise is optional.",
    "Skip it if you are short on sleep, have difficulty returning to sleep, or need uninterrupted rest.",
    "If you choose to try it, set an alarm for about six hours after you expect to fall asleep.",
    "When you wake, stay up only briefly, keep yourself sleepy, and use one short intention: I remain aware as I return to sleep.",
    "Return to bed, then use relax, one anchor, one motion, reduce effort, and sleep.",
    "If you skip the alarm, use the same compressed sequence at a natural awakening or at bedtime.",
  ],
  [
    "Choose one anchor that requires a little more active tracking: count breaths from 1 to 10, or trace one slow tactile path repeatedly.",
    "Keep the anchor for several minutes, then add one familiar motion.",
    "After the motion is clear, reduce effort.",
    "Do not try to stay awake indefinitely.",
  ],
  [
    "Do not count.",
    "Do not cycle senses.",
    "Do not rehearse several movements.",
    "Relax, choose one simple motion, make it faint, and let thoughts and imagery drift around it.",
    "If the motion disappears, do not immediately rebuild it.",
    "Rest.",
  ],
  [
    "Before tonight’s attempt, pick one route and commit to it for the whole try.",
    "The sensory route: start with one tactile anchor, move to whole-body sensation, then one motion.",
    "The observation route: watch, listen, or feel; let imagery arise; then one motion.",
    "The lucid route: use MILD to recognize the dream, then one motion.",
    "Natural awakening: wake from a dream, stay comfortable, use one motion, and return to sleep.",
    "Minimal: relax, then one motion.",
    "Choose before the attempt.",
    "Do not switch routes because nothing happens immediately.",
  ],
  [
    "Choose one entry based on your own experience: a sensory entry with one tactile anchor; observation by watching, listening, or feeling; a lucid entry with MILD intention; motion with one familiar imagined movement; or natural awakening only if you wake from a dream.",
    "Choose the easiest one to begin—not the most dramatic—and use that entry for a few minutes.",
    "Then add one familiar motion if it fits, reduce effort, and allow sleep.",
  ],
  [
    "Repeat the same route you have been using, but remove one part you do not seem to need.",
    "For example, go from sensory anchor straight to motion; from observation straight to motion; from MILD straight to sleep; or from natural awakening straight to motion.",
    "Do not replace the removed step with something new.",
    "Try the simpler version and let sleep come.",
  ],
  [
    "Choose one sentence before you begin—for example: I remain aware as sleep begins; When I dream, I recognize it; I follow the movement; or I return to sleep with awareness.",
    "Choose one, then stop giving yourself instructions and use the simplest version of your method.",
  ],
  [
    "Use your personal method.",
    "If something begins to change naturally—imagery, sound, body sense, movement, dream scene, self-location, or lucidity—stop adding steps and follow the change already happening.",
    "If nothing changes, continue lightly and sleep.",
  ],
  [
    "Choose one entry and one action, and use only those two parts.",
    "Examples include palm sensation then float, breath then roll, MILD then recognize, visual field then rise, or natural awakening then move toward a point.",
    "Do not add a second technique, a rescue sequence, or restart unless you become fully awake.",
  ],
  [
    "Before you sleep tonight, decide your plan in plain terms: when you will start, how you will enter the practice, any anchor or movement you want to include, whether you will set a brief MILD intention, and when you will stop effort and let sleep take over.",
    "Keep the plan simple.",
    "Perform one attempt, then sleep.",
  ],
] as const;

export function guidedDoThisForDay(day: number): readonly string[] {
  if (day < 1 || day > 60) return [];
  return GUIDED_DO_THIS[day - 1] ?? [];
}
